---
title: "Coronavirus disease 2019"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(leaflet)
library(leafpop)
library(tidyverse)

# colors
confirmed_color <- "#627D98"
active_color    <- "#E12D39"
recovered_color <- "#07818F"
death_color     <- "#3E4C59"
color_def <- list(
  confirmed = confirmed_color,
  active    = active_color,
  recovered = recovered_color,
  death     = death_color
)

# data
library(coronavirus)
data(coronavirus)

total <-
  coronavirus %>%
  group_by(country, province, lat, long, type) %>%
  summarise(cases = sum(cases, na.rm = T)) %>%
  pivot_wider(names_from = type,
              values_from = cases) %>%
  ungroup() %>%
  mutate(active = confirmed - recovered - death) %>%
  arrange(desc(active)) %>%
  mutate(rank = dense_rank(desc(active)))

jp_confirmed <- total$confirmed[total$country == 'Japan']
jp_recovered <- total$recovered[total$country == 'Japan']
jp_death     <- total$death[total$country == 'Japan']
jp_active    <- jp_confirmed - jp_death - jp_recovered
jp_daily <-
  coronavirus %>%
  filter(country == 'Japan') %>%
  select(date, type, cases) %>%
  pivot_wider(names_from = type,
              values_from = cases) %>%
  mutate(confirmed_cum = cumsum(confirmed),
         death_cum = cumsum(death),
         recovered_cum = cumsum(recovered),
         active_cum = confirmed_cum - death_cum - recovered_cum)
```

Japan
===============================================================================

Row
-------------------------------------------------------------------------------
### confirmed {.value-box}
```{r}
valueBox(
  value = format(jp_confirmed, big.mark = ","),
  caption = "Total cases",
  icon = "fas fa-user-md",
  color = confirmed_color
)
```

### active {.value-box}
```{r}
valueBox(
  value = format(jp_active, big.mark = ","),
  caption = "Active",
  icon = "fas fa-procedures",
  color = active_color
)
```


### recovered {.value-box}
```{r}
valueBox(
  value = format(jp_recovered, big.mark = ","),
  caption = "Recovered",
  icon = "fas fa-heart",
  color = recovered_color
)
```

### death {.value-box}
```{r}
valueBox(
  value = 
    paste(
      format(jp_death, big.mark = ","), 
      " (",
      round(jp_death / jp_confirmed * 100, 1),
      "%)",
      sep = ""
    ),
  caption = "Death",
  icon = "fas fa-skull",
  color = death_color
)
```


Row
-------------------------------------------------------------------------------
### **Number of patients in Japan**
```{r}
jp_daily %>%
  plotly::plot_ly(
    x = ~ date,
    y = ~ confirmed,
    type = "bar",
    name = "New case",
    marker = list(color = confirmed_color)
  ) %>%
  plotly::add_paths(
    y = ~ active_cum,
    name = "Active",
    marker = list(color = active_color)
  ) %>%
  plotly::add_paths(
    y = ~ recovered_cum,
    name = "Recovered",
    marker = list(color = recovered_color)
  ) %>%
  plotly::add_paths(
    y = ~ death_cum,
    name = "Death",
    marker = list(color = death_color)
  ) %>%
  plotly::layout(
    title = "",
    legend = list(x = 0.05, y = 1.00),
    yaxis = list(title = ""),
    xaxis = list(title = ""),
    hovermode = "compare"
  )
```


World
===============================================================================
### **Number of cases as of `r format(max(coronavirus$date), "%d %B %Y")`**
```{r}
total %>%
  filter(rank <= 30) %>%
  plotly::plot_ly(
    x = ~ reorder(country, desc(active)),
    y = ~ active,
    type = "bar",
    name = "Active",
    marker = list(color = active_color)
  ) %>%
  plotly::add_trace(
    y = ~ recovered,
    name = "Recovered",
    marker = list(color = recovered_color)
  ) %>%
  plotly::add_trace(
    y = ~ death,
    name = "Death",
    marker = list(color = death_color)
  ) %>%
  plotly::layout(
    barmode = "group",
    legend = list(x = 0.95, y = 1.00),
    yaxis = list(title = ""),
    xaxis = list(title = ""),
    hovermode = "compare"
  )
```


World Map
===============================================================================
### World map
```{r}
total_4_map <-
  total %>%
  select(-confirmed, -rank) %>%
  pivot_longer(cols = c('active', 'recovered', 'death'),
               names_to = 'type',
               values_to = 'cases') %>%
  mutate(log_cases = case_when(cases <= 0   ~ 0,
                               is.na(cases) ~ 0,
                               TRUE         ~ 3 * log(cases)))

types_rendered <- c('active', 'recovered', 'death')

map_object <-
  leaflet() %>% 
  addProviderTiles(providers$Esri.WorldGrayCanvas)

walk(types_rendered, function(type_) {
  map_object <<-
    map_object %>%
    addCircleMarkers(
      data = total_4_map %>% filter(type == type_),
      lng = ~ long,
      lat = ~ lat,
      color = ~ color_def[[type_]],
      stroke = FALSE,
      fillOpacity = 0.8,
      radius = ~ log_cases,
      popup = leafpop::popupTable(
        total_4_map %>% filter(type == type_),
        feature.id = FALSE,
        row.numbers = FALSE,
        zcol = c("type", "cases", "country", "province")
      ),
      group = type_,
      labelOptions = labelOptions(
        noHide = F,
        direction = "auto"
      )
    )
})

map_object %>%
  addLayersControl(overlayGroups = types_rendered,
                   options = layersControlOptions(collapsed = FALSE)) %>%
  hideGroup(types_rendered[-1])
```


About
===============================================================================

**Code**

[github.com/watanabe8760/coronavirus_dashboard](https://github.com/watanabe8760/coronavirus_dashboard){target="_blank"}.

**Data**

[`{coronavirus}`](https://github.com/RamiKrispin/coronavirus){target="_blank"}


**Update**

The data is as of `r format(max(coronavirus$date), "%d %B %Y")` and the dashboard has been updated on `r format(Sys.time(), "%d %B %Y")`.

